# Generated by Django 3.2.9 on 2021-12-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0002_lop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoSuuTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KichThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiGa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiNem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True)),
                ('image', models.ImageField(upload_to='ImageProduct')),
                ('slug', models.SlugField(unique=True)),
                ('boSuuTap', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.bosuutap')),
                ('chatLieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dulieu.chatlieu')),
                ('doDay', models.ManyToManyField(to='dulieu.DoDay')),
                ('kichThuoc', models.ManyToManyField(to='dulieu.KichThuoc')),
                ('loaiGa', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.loaiga')),
                ('loaiNem', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.loainem')),
                ('thuongHieu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.thuonghieu')),
            ],
        ),
    ]
