# Generated by Django 3.2.9 on 2021-12-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0003_bosuutap_chatlieu_doday_kichthuoc_loaiga_loainem_product_thuonghieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosuutap',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatlieu',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doday',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kichthuoc',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loaiga',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loainem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='thuonghieu',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='boSuuTap',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dulieu.bosuutap'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loaiGa',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dulieu.loaiga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loaiNem',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dulieu.loainem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thuongHieu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dulieu.thuonghieu'),
        ),
    ]
