# Generated by Django 3.2.9 on 2021-12-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0004_auto_20211228_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boSuuTap',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.bosuutap'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='loaiGa',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.loaiga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='loaiNem',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.loainem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thuongHieu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dulieu.thuonghieu'),
        ),
    ]
