# Generated by Django 3.2.9 on 2022-01-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0010_order_kichthuoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='kichthuoc',
            new_name='doday',
        ),
    ]
