# Generated by Django 3.2.9 on 2022-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0011_rename_kichthuoc_order_doday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HocSinh',
        ),
        migrations.DeleteModel(
            name='Lop',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
