# Generated by Django 3.2.9 on 2022-03-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulieu', '0018_likeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeproduct',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
